#!/usr/bin/env bash
# setup haproxy

sudo apt update
sudo apt install haproxy -y

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 274841-web-01 54.236.12.209 check
   server 274841-web-02 18.206.232.102 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
