#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server STUDENT_ID-web-01 54.236.12.209 check
   server STUDENT_ID-web-02 18.206.232.102 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
